server:
  port: 8080

spring:
  freemarker:
    suffix: .ftl
    cache: false
    settings:
      template_update_delay: 0
  mvc:
    static-path-pattern: "/static/**"

com:
  bailizhang:
    lynxdb:
      host: "127.0.0.1"
      port: 7820